### PR TITLE
HMT-63 Judging Dashboard

### PR DESCRIPTION
**Pull request by hannagracec**
Added the dashboard for judges to display the teams that are assigned to their room. Includes stats panels displaying number of teams assigned to their room and number of teams left to score. The scoring table displays the team names, has a column for each scoring component, has a sort button to switch between alphabetical and reverse alphabetical order, and includes pagination.

The scoring table can be reused for the Admin side. There are props to edit the colour scheme (either pink or purple) and determine how many entries are shown per page (since there are more entries shown to admins).

image

A popup opens when clicking the create score button displaying the team name.
image

Similarly, with the edit score button, the team name will be displayed.
image

These popups can be changed once the scoring flow is made!

### CODE REVIEW

**Review by ideen1 — CHANGES_REQUESTED** [review]
Looks good overall, one question. I think I put all the right data in my tables but there wasn't an "add score" button that appeared when I had a team left to score, the table was just empty(not even the teams assigned to me showed up). Did I maybe forget to add something to one of my tables?

**Comment by hannagracec** [comment]
@ideen1 hmm that's weird, did anything show up in the console? If not, it does use quite a few different tables so just to double check there should be items in the teams, teamRoom, room, and Hackathon tables.

**Comment by ideen1** [comment]
@hannagracec Status update: still on my list will be testing shortly.

**Review by ideen1 — APPROVED** [review]
LGTM, to be tested in master after additional features are added

**Pull request merged**
