### PR TITLE
Admin and judge redirects to dashboard

### PR DESCRIPTION
**Pull request by burtonjong**

### CODE REVIEW

**Comment by burtonjong** [comment]
Does this based off user.role but if given role through cognito it wont work - could instead use usercontext to get the users role and instead currentuser.type (which is the role given through cognito) and could be more accurate - although I dont think well encounter a case where user.role != currentuser.type though but its possible

**Comment by ideen1** [comment]
> We still want the Admin/Judges to fill out the personal field form. For name as stuff, does this bypass that? We should only redirect them from the page that prompts them to join a team. @burtonjong

Both of these fields will always be the same. We should try to use the context as much as possible instead of one-off requests to the GetUser endpoint.


However, this brings up an important point. What does the flow look like when a judge signs up? When they first sign up they will be prompted for a team anyways because they are going to be marked a participant.(We should instruct them verbally to ignore this). One day this could be improved by having an invitation mechanism for judges or smth. On subsequent logins, they will be even the Judge role. We should just ensure that judges/admins are pushed to their dashboard when the join a team page shows up. That should cover most situations.

**Comment by burtonjong** [comment]
@ideen1 Now they are redirected only if they have completed registration. Thing is though judges will be participants at first (so will some admins if they have to sign up) so like you said later we can implement an invitation type of thing

**Review by ideen1 — APPROVED** [review]
This looks good. It will redirect judges/admins to their dashboard on subsequent logins

**Pull request merged**
