### PR TITLE
Hmt 9 thank sponsors

### PR DESCRIPTION
**Pull request by burtonjong**
Desktop View:
image

IPhone SE View:
image

IPhone XR View:
image

The reason why I added the IPhoneSE and IPhoneXR view is because of the improvisations that me and @nataliey16 made. When decreasing screen width, the squiggly lines move closer to the header but never end up overlapping. Hopefully this looks okay and am willing to take any feedback on it. 

When hovering an image, the sponsor name will appear under the image.
image

I also need feedback because on the CTC website, most of the sponsors images are not circular. Thus, if we do not have circular sponsor images some change will have to be made to accomodate for whatever shape they are. I also suggest (although if it looks fine then no changes need to be made) but the layout on the mobile view should not be a 5x1, but rather 2x2 or 2x3 (depending on the number of images).

### CODE REVIEW

**Review by ideen1 — COMMENTED** [review]
Can you merge main into your branch? There seems to be some significant changes with Headers and such that made on main since you made this branch that are preventing it from building on my machine.

**Comment by burtonjong** [comment]
Should work now

**Review by ideen1 — DISMISSED** [review]
LGTM!

**Review by ideen1 — DISMISSED** [review]
Re-adding approval

**Pull request merged**
