### PR TITLE
Issue #116 - Connected Ceremony Details to Contentful

### PR DESCRIPTION
**Pull request by hannagracec**

### CODE REVIEW

**Comment by ideen1** [comment]
Can you also address the ones in this comment: https://github.com/Code-the-Change-YYC/hackathon-management-tool/issues/116#issuecomment-2425574208

**Comment by hannagracec** [comment]
@ideen1 sorry I completely missed that, will do!

**Comment by ideen1** [comment]
@hannagracec No worries at all! Did you also do the part that changes the team name's judging info to the actual team name and judge time? You should be able to read the Team Rooms table for this

**Comment by burtonjong** [comment]
Dupe of #142

**Pull request closed without merging**
